### ISSUE TITLE
ModuleNotFoundError: No module named 'knet'

### ISSUE THREAD

**Issue by XavierCHEN34** [ZwwWayne/K-Net#20]
Training command is python /home/pai/lib/python3.6/site-packages/mmdet/.mim/tools/train.py ./configs/det/knet/knet_s3_r50_fpn_1x_coco-panoptic.py --gpus 1 --launcher none --work-dir ./tmp.
Traceback (most recent call last):
  File "/home/pai/lib/python3.6/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/pai/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'knet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pai/lib/python3.6/site-packages/mmdet/.mim/tools/train.py", line 185, in <module>
    main()
  File "/home/pai/lib/python3.6/site-packages/mmdet/.mim/tools/train.py", line 90, in main
    cfg = Config.fromfile(args.config)
  File "/home/pai/lib/python3.6/site-packages/mmcv/utils/config.py", line 334, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/pai/lib/python3.6/site-packages/mmcv/utils/misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError
Traceback (most recent call last):
  File "/home/pai/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/pai/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/pai/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pai/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pai/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pai/lib/python3.6/site-packages/mim/commands/train.py", line 107, in cli
    other_args=other_args)
  File "/home/pai/lib/python3.6/site-packages/mim/commands/train.py", line 256, in train
    cmd, env=dict(os.environ, MASTER_PORT=str(port)))
  File "/home/pai/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)

**Comment by XavierCHEN34** [comment]
wrong command script

**Comment by bxiang233** [comment]
> wrong command script

Hi, how did you solve this problem?

**Comment by sayoko17** [comment]
> > 错误的命令脚本
> 
> 你好，你是怎么解决这个问题的？

hello,i meet this problem too,could you tell me how to solve it
